spring:
  cloud:
    vault:
      uri: http://77.221.140.212:8201/
      connection-timeout: 5000
      read-timeout: 15000
      authentication: TOKEN
      token: token
      kv:
        application-name: database
        enabled: true
        backend: secret
        profile-separator: '/'
        default-context: database

  config:
    import: vault://